[sensors]
moist1.sensor_type = 'moist_sensor'
moist1.pwr_pin = 17
moist1.val_pin = 27
moist1.pwr_wait = 5
moist1.interval = 10
moist2.sensor_type = 'moist_sensor'
moist2.pwr_pin = 17
moist2.val_pin = 27
moist2.pwr_wait = 5
moist2.interval = 10
